# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Megumi's Blog
name: Zuoyu Liang
email: lzykun@mail.ustc.edu.cn
location: Shanghai
company: USTC
github_url: https://github.com/KatouMegumiMoe
github_username: KatouMegumiMoe
description: Megumi's Blog
favicon: favicon.png # Image must be in assets/images
repository: KatouMegumiMoe/KatouMegumiMoe.github.io
about_me: 毕业于中国科学技术大学软件工程系，数据挖掘/算法工程师。

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url.
# url: https://katoumegumimoe.github.io
# local running with command 'bundle exec jekyll serve'
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings

# Pagination
paginate: 5
paginate_path: 'page:num'

navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Photos

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Technology

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 3 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_programming_language_keywords: [Java, Python, Scala, C, Pascal]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
